---
name: test-macos
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    name: "[test] [macos]"
    steps:
      # ------------------------------------------------------------
      # Setup
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------------------------------------------
      # Tests: Behaviour
      # ------------------------------------------------------------
      - name: test
        shell: bash
        run: |
          make test
